server:
  port: 8080

spring:
#  cloud:
#    azure:
#      active-directory:
#        enabled: true
#        profile:
#          tenant-id: 9bffabe1-4682-4566-ba5e-72e9f0f12789
#        credential:
#          client-id: 814b8b59-c139-4c3b-b10d-328b6c4f90d3
#          client-secret: 493da0b6-87af-44f3-b977-0f9506588e6a
#        app-id-uri: api://814b8b59-c139-4c3b-b10d-328b6c4f90d3/read
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/9bffabe1-4682-4566-ba5e-72e9f0f12789/discovery/v2.0/keys
